version: '3.5'

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    container_name: mongo-user
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminLinh
      MONGO_INITDB_ROOT_PASSWORD: linhporo1
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-data:/data/db

  redis:
    image: redis
    container_name: redis-user
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data


